### PR TITLE
s3ve3g-common: audio: update mixer_paths values

### PR DESCRIPTION
**Pull request by iBullRay**
* Return speaker volume to stock value.
* Raise speaker volume in calls.

Signed-off-by: iBullRay <bullray097@yandex.ru>

### CODE REVIEW

**Comment by djmanri3** [comment]
can use for s3ve3gxx??

**Comment by iBullRay** [comment]
@djmanri3 
Doesn't matter. Works on s3ve3gxx, s3ve3gds, s3ve3gjv.

**Comment by djmanri3** [comment]
Okay thanks

**Comment by haggertk** [comment]
Code changes to LineageOS are submitted through Gerrit - https://wiki.lineageos.org/how-to/submitting-patches

**Pull request closed without merging**
